<?php

declare(strict_types=1);

namespace Camelot\Arbitration\Generator;

use Camelot\Arbitration\Configuration\Rendition;
use Camelot\Arbitration\Filesystem\FileInfo;

/**
 * Generates relative path names for images rendered by the library.
 *
 * The methods generate() and resolve() MUST be able to find each other's reverse-value.
 */
interface PathnameGeneratorInterface
{
    /** Return a relative base path to all files generated by this rendition */
    public function base(Rendition $rendition): string;

    /** Generate a relative path name for a rendered image. */
    public function generate(FileInfo $source, Rendition $rendition): string;

    /** Given the relative path of the $render object, resolve the original file path name. */
    public function resolve(FileInfo $render): string;

    public function resolveRendition(FileInfo $source): string;
}
